namn = input("Hej, vad heter du? ")
print(namn,"är ett fint namn. ")
mat = input(namn + " vilken mat gillar du? ")
print(namn, mat, "är verkligen gott. ")
pengar = input(namn + " hur mycket pengar har du? ")
print(namn, "du är rik ")